GET http://localhost:8080/mechanic
Accept: application/json

###

GET http://localhost:8080/mechanic/contact?idMechanic=3
Accept: application/json

###

POST http://localhost:8080/mechanic
Accept: application/json
Content-Type: application/json

{
  "idUser": 2,
  "idMechanic": 1,
  "score": 5
}