GET http://localhost:8080/person
Accept: application/json

###

POST http://localhost:8080/person
Accept: application/json
Content-Type: application/json

{
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321"
}

###

PUT http://localhost:8080/person
Accept: application/json
Content-Type: application/json

{
  "idPerson": 1,
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321"
}