GET http://localhost:8080/publications/?n=5&i=0
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/publications/brands
Accept: application/json
Content-Type: application/json


###
POST http://localhost:8080/publications
Accept: application/json
Content-Type: application/json

{
  "idBrand": 1,
  "idColor": 1,
  "idCity": 1,
  "title": "Title 2",
  "model": 2018,
  "doorNumber": 5,
  "licensePlate": "4089ZPLP",
  "description": "Hermoso auto con todas las prestaciones y confort",
  "motor": "1600cc",
  "price": 15000.500
}

###

PUT http://localhost:8080/publications
Accept: application/json
Content-Type: application/json

{
  "idPublication": 3,
  "idSeller": 1,
  "idBrand": 1,
  "idColor": 1,
  "idCity": 1,
  "title": "Toyota Rav4 2016",
  "model": 2018,
  "doorNumber": 5,
  "licensePlate": "4089ZPLP",
  "description": "Hermoso auto con todas las prestaciones y confort",
  "motor": "1600cc",
  "price": 15000.500
}

###


DELETE http://localhost:8080/publications?idPublication=1
Accept: application/json