POST http://localhost:8080/user/signin
Accept: application/json
Content-Type: application/json

{
  "email": "pomaalvin@gmail.com",
  "password": "1234abc"
}

###
GET http://localhost:8080/seller
Accept: application/json

###

POST http://localhost:8080/seller
Accept: application/json
Content-Type: application/json
{
  "idSeller": 4,
  "idPerson": 4,
  "idUser": 4,
  "password": "12345",
  "email": "456985",
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321",
  "imagePath": "Hermoso auto con todas las prestaciones y confort"
}
###

PUT http://localhost:8080/seller/image
Accept: application/json
Content-Type: application/json

{
  "idSeller": 4
}

###

PUT http://localhost:8080/seller
Accept: application/json
Content-Type: application/json

{
  "idSeller": 4,
  "idPerson": 4,
  "idUser": 4,
  "password": "456987",
  "email": "jhf@gmail.com",
  "firstName": "Silvana Stephanie",
  "lastName": "Munoz",
  "phoneNumber": "456321",
  "imagePath": "hello.com"
}
###
GET http://localhost:8080/seller/publications?i=0&n=10
Accept: application/json